	<!-- Begin header -->
	<div id="header">
		<h1 id="logo"><a href="<?=$gd->root_domain?>/" title="KOBUN PRINTING"><img src="/images/logo.gif" width="168" height="41" alt="KOBUN PRINTING" /></a></h1>
		<!-- Begin globalNavi -->
		<div id="globalNavi">
		<ul>
		<li class="gn1"><a href="<?=$gd->root_domain?>/news/" title="お知らせ">お知らせ</a></li>
		<li class="gn2"><a href="<?=$gd->root_domain?>/business/" title="事業案内">事業案内</a></li>
		<li class="gn3"><a href="<?=$gd->root_domain?>/corporate/" title="会社情報">会社情報</a></li>
		<li class="gn4"><a href="<?=$gd->root_domain?>/recruit/" title="採用情報">採用情報</a></li>
		</ul>
		</div>
		<!-- End globalNavi -->
	</div>
	<!-- End header -->
