		<div id="navi">
			<div class="naviBlock">
				<div id="logo"><img src="/images/morita_logo.gif" width="171" height="53" alt="森田アルミ工業"></div>
				<div><img src="/images/morita_copy.gif" width="205" height="10" alt="アルミ階段・エクステリア製品の製造メーカー"></div>
				<?php require_once("../include/globalnavi.inc");?>
				<div class="sideNaviBlock">
					<div class="title"><span class="rt"><strong>インテリア</strong></span></div>
					<ul class="product">
						<li><a href="/template/"><span class="title1"><span class="rt">TAS Glass Step</span></span><span class="subTitle"><span class="st">ガラス階段</span></span></a></li>
						<li><a href="/template/"><span class="title1"><span class="rt">TAS Wood Step</span></span><span class="subTitle"><span class="st">木製アルミ階段</span></span></a></li>
						<li><a href="/template/"><span class="title1"><span class="rt">TAS Hand rail</span></span><span class="subTitle"><span class="st">アルミ手摺</span></span></a></li>
						<li><a href="/template/"><span class="title1"><span class="rt">pid</span></span><span class="subTitle"><span class="st">室内物干しワイヤー</span></span></a></li>
						<li><a href="/template/"><span class="title1"><span class="rt">albase</span></span><span class="subTitle"><span class="st">アルミ巾木</span></span></a></li>
						<li><a href="/template/"><span class="title1"><span class="rt">falce</span></span><span class="subTitle"><span class="st">パーテーション</span></span></a></li>
					</ul>
					<div class="title"><span class="rt"><strong>エクステリア</strong></span></div>
					<ul class="product">
						<li><a href="/template/"><span class="title1"><span class="rt">SOL</span></span><span class="subTitle"><span class="st">面格子</span></span></a></li>
						<li><a href="/template/"><span class="title1"><span class="rt">ステアーズ</span></span><span class="subTitle"><span class="st">外部アルミ階段</span></span></a></li>
						<li><a href="/template/"><span class="title1"><span class="rt">パンチスクリーン</span></span><span class="subTitle"><span class="st">スクリーン</span></span></a></li>
						<li><a href="/template/"><span class="title2"><span class="rt">エアリー</span></span></a></li>
						<li><a href="/template/"><span class="title2"><span class="rt">テラス</span></span></a></li>
						<li><a href="/template/"><span class="title2"><span class="rt">手摺付笠木</span></span></a></li>
						<li><a href="/template/"><span class="title2"><span class="rt">アルミ笠木・下端水切り</span></span></a></li>
					</ul>
				</div><!-- End productNaviBlock -->
			</div><!-- End naviBlock -->
		</div><!-- End navi -->