	<!-- Begin footer -->
	<div id="footer">
		<div class="footerBlock">
			<div class="footerMenu">
				<div class="logoBlock">
					<div class="footerLogo"><a href="/"><img src="/images/footer_logo.gif" width="132" height="12" alt="森田アルミ工業株式会社"></a></div>
					<div class="copyright"><img src="/images/copyright.gif" width="218" height="8" alt="Copyright © morita aluminum industry ,inc. All rights reserved."></div>
				</div>
				<div class="footerMenuBlock">
					<ul>
						<li class="privacy"><a href="/privacy/">個人情報保護方針</a></li>
						<li class="contact"><a href="https://f.msgs.jp/webapp/hear/org/showEnquete.do?enqueteid=3&clientid=11230&databaseid=ypq">お問い合わせ</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<!-- End footer -->
</div><!-- End CT -->
		<div id="PAGETOP"><a href="#CT" title="pagetop" onclick="scrTar(0,0); return false;">PAGETOP</a></div>
</body>
</html>