		<div id="globalNavi">
		<ul>
		<li class="gn1"><a href="/news/" title="お知らせ" class="commonBtn"><img src="/images/gnav_news.gif" alt="お知らせ"></a></li>
		<li class="gn2"><a href="/works/" title="製品紹介" class="commonBtn"><img src="/images/gnav_product.gif" alt="お知らせ"></a></li>
		<li class="gn3"><a href="/corporate/" title="企業情報" class="commonBtn"><img src="/images/gnav_corporate.gif" alt="お知らせ"></a></li>
		<li class="gn4"><a href="https://f.msgs.jp/webapp/hear/org/showEnquete.do?enqueteid=2&clientid=11230&databaseid=ypq" title="資料請求" class="commonBtn"><img src="/images/gnav_request.gif" alt="お知らせ"></a></li>
		</ul>
		</div>

