<?php
/*Begin works */
require_once( $_SERVER['DOCUMENT_ROOT'] . "/gdCMS/conf/gd.conf");
require_once( _PATH_gdCMS_ROOT . "gdF/gdF.conf");
require_once( $_SERVER['DOCUMENT_ROOT'] . "/lib/ProductNewsCollection.class.inc");
/*End works */
?>
		<div id="header-container">
			<div class="header">
				<div id="logo"><a href="/"><img src="/images/morita_logo.gif" width="164" height="55" alt="森田アルミ工業"></a></div>
			<div id="globalNavi">
					<ul>
						<li class="gn1"><a href="/news/" title="お知らせ" class="commonBtn"><img src="/images/gnav_news.gif" alt="お知らせ"></a></li>
						<li class="gn2"><a href="/works/" title="製品紹介" class="commonBtn"><img src="/images/gnav_product.gif" alt="お知らせ"></a></li>
						<li class="gn3"><a href="/corporate/" title="企業情報" class="commonBtn"><img src="/images/gnav_corporate.gif" alt="お知らせ"></a></li>
						<li class="gn4"><a href="https://f.msgs.jp/webapp/hear/org/showEnquete.do?enqueteid=2&clientid=11230&databaseid=ypq" title="資料請求" class="commonBtn"><img src="/images/gnav_request.gif" alt="お知らせ"></a></li>
					</ul>
				</div>
				<div class="copy"><img src="/images/morita_copy.gif" width="141" height="11" alt="時代や国境を越える価値を"></div>

			</div><!-- End header -->
		</div><!-- End header-container -->